FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

COPY config/requirements.txt .

RUN pip install -r requirements.txt

COPY ./ /Modeling_App
WORKDIR /Modeling_App/app

ENV PYTHONPATH=/Modeling_App

EXPOSE 8888